CREATE TABLE bed (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	room_number VARCHAR(50) NOT NULL,
	bed_number VARCHAR(50) NOT NULL,
	status VARCHAR(20) NOT NULL, -- Change from TINYINT to VARCHAR
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);